routes/admin.php
<?php

use App\Models\Region;
use App\Models\Category;
use App\Models\District;
use App\Models\FilterGroup;
use App\Models\Governorate;
use Illuminate\Http\Request;
use App\Models\Advertisement;
use App\Http\Controllers\Admin\FiltersController;
use App\Http\Controllers\Admin\RegionsController;
use App\Http\Controllers\Admin\DistrictsController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\CustomAuthController;
use App\Http\Controllers\Admin\GovernoratesController;
use App\Http\Controllers\Admin\AdvertisementsController;
require 'breadcrumbs.php';



Route::get('login',[CustomAuthController::class,'login'])->name('login');
Route::get('signup',[CustomAuthController::class,'signup'])->name('signup');
Route::post('postlogin',[CustomAuthController::class,'postlogin'])->name('postlogin'); 
Route::post('signupsave', [CustomAuthController::class,'signupsave'])->name('signupsave'); 
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath','auth' ]
    ], function(){
        Route::resource('governorates', GovernoratesController::class);
        Route::resource('regions', RegionsController::class);
        Route::resource('districts', DistrictsController::class);
        Route::resource('filters', FiltersController::class);
        Route::resource('advertisements', AdvertisementsController::class);
        Route::resource('categories', CategoriesController::class);
        Route::get('getFilters', function (Request $request) {
            $filterGroups = FilterGroup::whereHas('categories', function ($q) use ($request) {
                $q->where('category_id', $request->category_id);
            })->get();
            return view('admin.advertisements.getFilters', compact('filterGroups'));
        })->name('getFilters');

        Route::get('getRegions', function (Request $request) {
            $regions = Region::where('governorate_id', $request->governorate_id)->where('status', 'enabled')->get();
            return view('admin.districts.getRegions', compact('regions'));
        })->name('getRegions');

        Route::get('getDistricts', function (Request $request) {
            $districts = District::where('region_id', $request->region_id)->where('status', 'enabled')->get();
            return view('admin.districts.getDistricts', compact('districts'));
        })->name('getDistricts');
        Route::controller(CustomAuthController::class)->group(function () {
            Route::get('/','home')->name('home'); 
            Route::get('dashboard','dashboard'); 
            Route::get('signout', 'signOut')->name('signout');
            Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
            Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
            Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
            Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
        });
        
    });
    Route::get('home', function () {
        $categories = Category::all();
        $advertisements = Advertisement::all();
        return view('web.home', compact('categories','advertisements'));
    })->name('home');

    Route::get('getgovernorates', function (Request $request) {
        $datas = Governorate::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->get();
        $clickclass = 'governorates';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getgovernorates');

    Route::get('getregions', function (Request $request) {
        $datas = Region::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id)->where('governorate_id',  $request->governorate_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->get();
        $clickclass = 'regions';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getregions');

    Route::get('getdistricts', function (Request $request) {
        $datas = District::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id)->where('governorate_id', $request->governorate_id)
            ->where('region_id', $request->region_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->
        where('region_id', $request->region_id)->get();
        $clickclass = 'districts';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getdistricts');

    Route::get('getdata', function (Request $request) {
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->
        where('region_id', $request->region_id)->
        where('district_id', $request->district_id)->get();
        $filterGroups = FilterGroup::whereHas('categories', function ($q) use ($request) {
            $q->where('category_id', $request->category_id);
        })->get();
        return view('web.advertisements', compact('advertisements','filterGroups'));
    })->name('getdata');

    // Route::get('web','web/index')->name('home');
// Route::controller(WebController::class)->group(function () {

//     // Route::get('dashboard','dashboard'); 
//     // Route::get('signout', 'signOut')->name('signout');
//     // Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
//     // Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
//     // Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
//     // Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
// });


// Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth', 'checkLogin']], function () {

//     Route::get('/', function () {
//         return view('dashboard.layouts.layout');
//     })->name('index');


//     Route::get('/settings', [SettingController::class, 'index'])->name('settings');

//     Route::post('/settings/update/{setting}', [SettingController::class, 'update'])->name('settings.update');


//     Route::get('/users/all', [UserController::class, 'getUsersDatatable'])->name('users.all');
//     Route::post('/users/delete', [UserController::class, 'delete'])->name('users.delete');


//     Route::get('/category/all', [CategoryController::class, 'getCategoriesDatatable'])->name('category.all');
//     Route::post('/category/delete', [CategoryController::class, 'delete'])->name('category.delete');



//     Route::get('/posts/all', [PostsController::class, 'getPostsDatatable'])->name('posts.all');
//     Route::post('/posts/delete', [PostsController::class, 'delete'])->name('posts.delete');


//     Route::resources([
//         'users' => UserController::class,
//         'category' => CategoryController::class,
//         'posts' => PostsController::class,
//     ]);
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('/', function () {
//     return view('admin.index');
// });

// Route::get('/app', function () {
//     return view('admin.app');
// });


// Route::get('/gest', function () {
//     return view('admin.gest');
// });

// Route::get('/login', function () {
//     return view('admin.auth.login');
// });


// Route::get('/register', function () {
//     return view('admin.auth.register');
// });


// Route::get('/forgot', function () {
//     return view('admin.auth.forgot');
// });


// Route::get('/reset', function () {
//     return view('admin.auth.reset');
// });


// Route::get('/verify', function () {
//     return view('admin.auth.verify');
// }); 

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';
require __DIR__ . '/api.php';


// Route::get('/', [IndexController::class, 'index'])->name('index');
// Route::get('/categories/{category}', [WebsiteCategoryController::class, 'show'])->name('category');
// Route::get('/post/{post}', [PostController::class, 'show'])->name('post');

app/Models/District.php
<?php

namespace App\Models;
use App\Models\Region;
use App\Models\Advertisement;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class District extends Model
{
    use HasFactory;
    protected $fillable = ['name','status','region_id'];

   

    public function region()
    {
    	return $this->belongsTo(Region::class);
    }

    public function advertisements()
    {
    	return $this->hasMany(Advertisement::class);
    }

}

app/Http/Controllers/Admin/DistrictsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Region;
use App\Models\District;
use App\Models\Governorate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\DistrictsRequest;



class DistrictsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get all the Category
        $districts = District::all();
        return view('admin.districts.index', compact('districts'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $governorates = Governorate::where('status', 'enabled')->get();
        return view('admin.districts.create', compact('governorates'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DistrictsRequest $request)
    {
        District::create($request->validated());
        return redirect('districts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       
        $district = District::find($id);
        $region = Region::find($district->region_id);
        $governorates = Governorate::where('status', 'enabled')->get();
        $regions = Region::where('status', 'enabled')->where('governorate_id', $region->governorate_id)->get();
        return view('admin.districts.edit', compact('governorates','regions', 'region', 'district'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(DistrictsRequest $request, District $district) {
        $district->update($request->validated());
        return redirect('regions');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(District $district)
    {
        $district->delete();
        return redirect()->back();
    }
}

resources/views/admin/districts/create.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
   <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>

  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('districts.index') }}">@lang('districts')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('districts.create') }}" >@lang('Add New')</a>
</li>
@endsection


@section('content')
<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('districts.store') }}">
            @csrf
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Add New') @lang('district') </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('governorates')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="governorate_id" data-placeholder="" id="governorates" required>
                                <option value=""></option>
                                @foreach ($governorates as $governorate)
                                <option value="{{  $governorate->id }}">{{  $governorate->name }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Regions')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="region_id" data-placeholder="" id="regions" required>
                                <option value=""></option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Name')</label>
                                <input type="text" id="fp-default" name="name"  
                                class="form-control "
                                placeholder="@lang('Name')" />
                                @error('name')
                                <div class="text-danger">{{$message}}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Latitude')</label>
                                <input type="text" id="fp-default" name="latitude"  
                                class="form-control "
                                placeholder="@lang('Latitude')" />
                                @error('latitude')
                                <div class="text-danger">{{$message}}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Longitude')</label>
                                <input type="text" id="fp-default" name="longitude"  
                                class="form-control "
                                placeholder="@lang('Longitude')" />
                                @error('longitude')
                                <div class="text-danger">{{$message}}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" class="d-block">@lang('Status')</label>
                                <div class="form-check my-50">
                                    <input type="radio" id="validationRadio3" name="status" checked class="form-check-input" required  value="enabled"/>
                                    <label class="form-check-label" for="validationRadio3">@lang('Enabled')</label>
                                </div>
                                <div class="form-check">
                                    <input type="radio" id="validationRadio4" name="status" class="form-check-input" required  value="disabled"/>
                                    <label class="form-check-label" for="validationRadio4">@lang('Disabled')</label>
                                </div>
                            </div>
                        </div>   
                    </div>
                   
                
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!-- END: Theme JS-->
<script>
    $(document).ready(function() {
        $('.select2').select2();
        $(document).on('change',"#governorates", function () {
            var governorate_id = $(this).val();
            $.ajax({
                type: 'get',
                url: "{{ route('getRegions') }}",
                data: {
                    governorate_id: governorate_id
                },
                success: function(data) {
                    if(data){
                        $('#regions').html(data);
                        $('.select2').select2();
                    }
                }
            });
            
        });
    });
</script>
@endsection

resources/views/admin/districts/edit.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
   <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>

  <!-- END: Page CSS-->
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('districts.index') }}">@lang('Districts')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('districts.create') }}" >@lang('Modify')</a>
</li>
@endsection

@section('content')
<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('districts.update', $district) }}">
            @csrf
            @method('PUT')
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Add New') @lang('District') </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Name')</label>
                                <input type="text" id="fp-default" name="name" required 
                                class="form-control " value="{{ $district->name  }}"
                                placeholder="Name" />
                            </div>
                        </div>

                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('governorates')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="governorate_id" data-placeholder="" required id="governorates">
                                @foreach ($governorates as $governorate)
                                <option value="{{  $governorate->id }}" @if ($governorate->id == $region->governorate_id)
                                    selected @endif>{{  $governorate->name }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div> 

                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('regions')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="region_id" data-placeholder="" required id='regions'>
                                @foreach ($regions as $region)
                                <option value="{{  $region->id }}" @if ($region->id == $district->region_id)
                                    selected @endif>{{  $region->name }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div> 
                    
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" class="d-block">@lang('Status')</label>
                                <div class="form-check my-50">
                                    <input type="radio" id="validationRadio3" name="status" @if ($district->status == 'enabled')
                                    checked @endif class="form-check-input" required  value="enabled"/>
                                    <label class="form-check-label" for="validationRadio3">@lang('Enabled')</label>
                                </div>
                                <div class="form-check">
                                    <input type="radio" @if ($district->status == 'disabled')
                                    checked @endif  id="validationRadio4" name="status" class="form-check-input" required  value="disabled"/>
                                    <label class="form-check-label" for="validationRadio4">@lang('Disabled')</label>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                   
                
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!-- END: Theme JS-->
<script>
    $(document).ready(function() {
        $('.select2').select2();
        $(document).on('change',"#governorates", function () {
            var governorate_id = $(this).val();
            $.ajax({
                type: 'get',
                url: "{{ route('getRegions') }}",
                data: {
                    governorate_id: governorate_id
                },
                success: function(data) {
                    if(data){
                        $('#regions').html(data);
                        $('.select2').select2();
                    }
                }
            });
            
        });
    });
</script>
@endsection

resources/views/admin/districts/getDistricts.blade.php
<option value=""></option>
@foreach ($districts as $district)
<option value="{{  $district->id }}"  >{{  $district->name }}</option>
@endforeach
                               

resources/views/admin/districts/getRegions.blade.php
<option value=""></option>
@foreach ($regions as $region)
<option value="{{  $region->id }}"  >{{  $region->name }}</option>
@endforeach
                               

resources/views/admin/districts/index.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('districts.index') }}">@lang('districts')</a>
</li>
@endsection

@section('content')
<div class="row" id="basic-table">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">@lang('districts')</h4>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li>
                            <a href="{{route('districts.create')}}"
                               class="btn btn-icon btn-primary waves-effect"
                               data-bs-toggle="tooltip"
                               data-bs-placement="left"
                               title="@lang('Add New')">
                                <i data-feather='plus-square'></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>@lang('Name')</th>
                        <th>@lang('Governorate')</th>
                        <th>@lang('Region')</th>
                        <th>@lang('status')</th>
                        <th class="width-150"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($districts as $district)
                        <tr>
                            <td>
                                <span class="fw-bold">{{$district->name}}</span>
                            </td>
                            <td>
                                <span class="fw-bold">{{$district->region->governorate->name}}</span>
                            </td>
                            <td>
                                <span class="fw-bold">{{$district->region->name}}</span>
                            </td>
                            <td>
                                <span class="fw-bold">{{$district->status}}</span>
                            </td>
                           
                            <td>


                                <a href="{{route('districts.edit',$district)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='edit'></i>
                                </a>
                            

                                {{ html()->form('DELETE',route('districts.destroy',$district))->class('d-inline')->open()}}
                                <button type="submit" class="btn btn-icon btn-outline-danger waves-effect confirm">
                                    <i data-feather='trash-2'></i>
                                </button>
                                {{ html()->form()->close()}}
                            </td> 
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center"></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/districts/show.blade.php
@extends('admin.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
     
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('View') @lang('Category') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('Name') </label>
                                    <p>{{ $Category->translate($key)->title ?? '' }} </p>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                    
                </div>
    
        </div>
    </div>
@endsection