routes/admin.php
<?php

use App\Models\Region;
use App\Models\Category;
use App\Models\District;
use App\Models\FilterGroup;
use App\Models\Governorate;
use Illuminate\Http\Request;
use App\Models\Advertisement;
use App\Http\Controllers\Admin\FiltersController;
use App\Http\Controllers\Admin\RegionsController;
use App\Http\Controllers\Admin\DistrictsController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\CustomAuthController;
use App\Http\Controllers\Admin\GovernoratesController;
use App\Http\Controllers\Admin\AdvertisementsController;
require 'breadcrumbs.php';



Route::get('login',[CustomAuthController::class,'login'])->name('login');
Route::get('signup',[CustomAuthController::class,'signup'])->name('signup');
Route::post('postlogin',[CustomAuthController::class,'postlogin'])->name('postlogin'); 
Route::post('signupsave', [CustomAuthController::class,'signupsave'])->name('signupsave'); 
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath','auth' ]
    ], function(){
        Route::resource('governorates', GovernoratesController::class);
        Route::resource('regions', RegionsController::class);
        Route::resource('districts', DistrictsController::class);
        Route::resource('filters', FiltersController::class);
        Route::resource('advertisements', AdvertisementsController::class);
        Route::resource('categories', CategoriesController::class);
        Route::get('getFilters', function (Request $request) {
            $filterGroups = FilterGroup::whereHas('categories', function ($q) use ($request) {
                $q->where('category_id', $request->category_id);
            })->get();
            return view('admin.advertisements.getFilters', compact('filterGroups'));
        })->name('getFilters');

        Route::get('getRegions', function (Request $request) {
            $regions = Region::where('governorate_id', $request->governorate_id)->where('status', 'enabled')->get();
            return view('admin.districts.getRegions', compact('regions'));
        })->name('getRegions');

        Route::get('getDistricts', function (Request $request) {
            $districts = District::where('region_id', $request->region_id)->where('status', 'enabled')->get();
            return view('admin.districts.getDistricts', compact('districts'));
        })->name('getDistricts');
        Route::controller(CustomAuthController::class)->group(function () {
            Route::get('/','home')->name('home'); 
            Route::get('dashboard','dashboard'); 
            Route::get('signout', 'signOut')->name('signout');
            Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
            Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
            Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
            Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
        });
        
    });
    Route::get('home', function () {
        $categories = Category::all();
        $advertisements = Advertisement::all();
        return view('web.home', compact('categories','advertisements'));
    })->name('home');

    Route::get('getgovernorates', function (Request $request) {
        $datas = Governorate::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->get();
        $clickclass = 'governorates';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getgovernorates');

    Route::get('getregions', function (Request $request) {
        $datas = Region::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id)->where('governorate_id',  $request->governorate_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->get();
        $clickclass = 'regions';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getregions');

    Route::get('getdistricts', function (Request $request) {
        $datas = District::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id)->where('governorate_id', $request->governorate_id)
            ->where('region_id', $request->region_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->
        where('region_id', $request->region_id)->get();
        $clickclass = 'districts';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getdistricts');

    Route::get('getdata', function (Request $request) {
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->
        where('region_id', $request->region_id)->
        where('district_id', $request->district_id)->get();
        $filterGroups = FilterGroup::whereHas('categories', function ($q) use ($request) {
            $q->where('category_id', $request->category_id);
        })->get();
        return view('web.advertisements', compact('advertisements','filterGroups'));
    })->name('getdata');

    // Route::get('web','web/index')->name('home');
// Route::controller(WebController::class)->group(function () {

//     // Route::get('dashboard','dashboard'); 
//     // Route::get('signout', 'signOut')->name('signout');
//     // Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
//     // Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
//     // Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
//     // Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
// });


// Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth', 'checkLogin']], function () {

//     Route::get('/', function () {
//         return view('dashboard.layouts.layout');
//     })->name('index');


//     Route::get('/settings', [SettingController::class, 'index'])->name('settings');

//     Route::post('/settings/update/{setting}', [SettingController::class, 'update'])->name('settings.update');


//     Route::get('/users/all', [UserController::class, 'getUsersDatatable'])->name('users.all');
//     Route::post('/users/delete', [UserController::class, 'delete'])->name('users.delete');


//     Route::get('/category/all', [CategoryController::class, 'getCategoriesDatatable'])->name('category.all');
//     Route::post('/category/delete', [CategoryController::class, 'delete'])->name('category.delete');



//     Route::get('/posts/all', [PostsController::class, 'getPostsDatatable'])->name('posts.all');
//     Route::post('/posts/delete', [PostsController::class, 'delete'])->name('posts.delete');


//     Route::resources([
//         'users' => UserController::class,
//         'category' => CategoryController::class,
//         'posts' => PostsController::class,
//     ]);
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('/', function () {
//     return view('admin.index');
// });

// Route::get('/app', function () {
//     return view('admin.app');
// });


// Route::get('/gest', function () {
//     return view('admin.gest');
// });

// Route::get('/login', function () {
//     return view('admin.auth.login');
// });


// Route::get('/register', function () {
//     return view('admin.auth.register');
// });


// Route::get('/forgot', function () {
//     return view('admin.auth.forgot');
// });


// Route::get('/reset', function () {
//     return view('admin.auth.reset');
// });


// Route::get('/verify', function () {
//     return view('admin.auth.verify');
// }); 

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';
require __DIR__ . '/api.php';


// Route::get('/', [IndexController::class, 'index'])->name('index');
// Route::get('/categories/{category}', [WebsiteCategoryController::class, 'show'])->name('category');
// Route::get('/post/{post}', [PostController::class, 'show'])->name('post');

app/Models/Filter.php
<?php

namespace App\Models;

use App\Models\FilterGroup;
use App\Models\Advertisement;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Filter extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'filter_group_id', 'status'];

    public function filterGroup()
    {
    	return $this->belongsTo(FilterGroup::class);
    }

    public function advertisements()
    {
        return $this->belongsToMany(Advertisement::class, 'advertisement_filter', 'filter_id','advertisement_id')->withPivot('val');
    }


   
}

app/Http/Controllers/Admin/FiltersController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Models\Filter;
use App\Models\FilterGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FiltersController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $filterGroups = FilterGroup::all();
        return view('admin.Filters.index', compact('filterGroups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.Filters.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $filtergroup = FilterGroup::create([
            'name' => $request->name,
            'type' => $request->type,
            'status' => $request->status
        ]);

        
        foreach ($request->invoice as $invoice) {
            
            Filter::create([
                'name' => $invoice['name'],
                'status' => $invoice['status'],
                'filter_group_id' => $filtergroup->id,
            ]);
        }
        return redirect('filters');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $filterGroup = FilterGroup::find($id);
        $filters = Filter::where('filter_group_id', $id)->get();
       
        return view('admin.filters.edit', compact('filterGroup','filters'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, FilterGroup $FilterGroup, $id)
    {
     

        $FilterGroup->update($request->all());
        foreach ($request->invoice as $invoice) {
            Filter::updateOrCreate([
                'name' => $invoice['name'],
                'status' => $invoice['status'],
                'filter_group_id' => $id,
            ]);
        }
        return redirect('filters');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(FilterGroup $FilterGroup)
    {
        $FilterGroup->delete();
        return redirect()->back();
    }
}

resources/views/admin/filters/create.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/vendors.min.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/pickers/pickadate/pickadate.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/core/menu/menu-types/vertical-menu.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/plugins/forms/pickers/form-pickadate.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/core/menu/menu-types/vertical-menu.css">
   <!-- END: Page CSS-->
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('filters.index') }}">@lang('Filters')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('filters.create') }}" >@lang('Add New')</a>
</li>
@endsection

@section('content')

 <section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('filters.store') }}" enctype="multipart/form-data">
            @csrf


            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Add New') @lang('Filter') </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        
                   

                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('filter group Name')</label>
                                <input type="text" id="fp-default" name="name" required 
                                class="form-control " placeholder="@lang('Name')" />
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('filter group Type')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="type" data-placeholder="">
                                <option value="1">checkbox</option>
                                <option value="2">tab</option>
                                <option value="3">val</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" class="d-block">@lang('Status')</label>
                                <div class="form-check my-50">
                                    <input type="radio" id="validationRadio3" name="status" checked class="form-check-input" required  value="enabled"/>
                                    <label class="form-check-label" for="validationRadio3">@lang('Enabled')</label>
                                </div>
                                <div class="form-check">
                                    <input type="radio" id="validationRadio4" name="status" class="form-check-input" required  value="disabled"/>
                                    <label class="form-check-label" for="validationRadio4">@lang('Disabled')</label>
                                </div>
                            </div>
                        </div>   
                    </div>
                
                </div>
               
            </div>
            <div class="form-control-repeater">
                <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">filter</h4>
                        </div>
                        <div class="card-body">
                            <div  class="invoice-repeater">
                                <div data-repeater-list="invoice">
                                    <div data-repeater-item>
                                        <div class="row d-flex align-items-end">
                                            <div class="col-md-6 col-12">
                                                <div class="mb-1">
                                                    <label class="form-label" for="itemname"> filter Name</label>
                                                    <input type="text" name="name" class="form-control" 
                                                    id="itemname" aria-describedby="itemname" placeholder="filter Name" />
                                                </div>
                                            </div>
                                            <div class="col-md-3 col-12">
                                                <div class="mb-1">
                                                    <label class="form-label" class="d-block">@lang('Status')</label>
                                                    <div class="form-check my-50">
                                                        <input type="radio" id="validationRadio3" name="status" checked class="form-check-input" required  value="enabled"/>
                                                        <label class="form-check-label" for="validationRadio3">@lang('Enabled')</label>
                                                    </div>
                                                    <div class="form-check">
                                                        <input type="radio" id="validationRadio4" name="status" class="form-check-input" required  value="disabled"/>
                                                        <label class="form-check-label" for="validationRadio4">@lang('Disabled')</label>
                                                    </div>
                                                </div>
                                            </div>   
                                            {{-- <div class="col-md-1 col-12">
                                                <div class="mb-1">
                                                    <div class="form-check">
                                                        <input type="checkbox" class="form-check-input" name="val"
                                                         id="validationCheckBootstrap"  value="1" />
                                                        <label class="form-check-label" for="validationCheckBootstrap">
                                                            Val</label>
                                                        <div class="invalid-feedback">Val</div>
                                                    </div>
                                                </div>
                                            </div> --}}

                                           

                                            <div class="col-md-2 col-12 mb-50">
                                                <div class="mb-1">
                                                    <button class="btn btn-outline-danger text-nowrap px-1" data-repeater-delete type="button">
                                                        <i data-feather="x" class="me-25"></i>
                                                        <span>Delete</span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <hr />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <button class="btn btn-icon btn-primary" type="button" data-repeater-create>
                                            <i data-feather="plus" class="me-25"></i>
                                            <span>Add New</span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <div class="card-footer">
                <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section> 
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.date.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.time.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/legacy.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js"></script>
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<script src="{{asset('admin')}}/app-assets/js/scripts/forms/pickers/form-pickers.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/forms/repeater/jquery.repeater.min.js"></script>
<script src="{{asset('admin')}}/app-assets/js/scripts/forms/form-repeater.js"></script>

<!-- END: Theme JS-->

@endsection

resources/views/admin/filters/index.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item active"><a href="{{ route('filters.index') }}">@lang('Filters')</a>
</li>
@endsection


@section('content')
<div class="row" id="basic-table">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">@lang('Filters')</h4>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li>
                            <a href="{{route('filters.create')}}"
                               class="btn btn-icon btn-primary waves-effect"
                               data-bs-toggle="tooltip"
                               data-bs-placement="left"
                               title="@lang('Add New')">
                                <i data-feather='plus-square'></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>@lang('Filter')</th>
                        <th class="width-150"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($filterGroups as $filterGroup)
                        <tr>
                            <td>
                                <span class="fw-bold">{{$filterGroup->name}}</span>
                            </td>
                           
                           
                            <td>

                                {{-- <a href="{{route('articles.show',$article)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='eye'></i>
                                </a> --}}


                                <a href="{{route('filters.edit',$filterGroup)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='edit'></i>
                                </a>
                            

                                {{ html()->form('DELETE',route('filters.destroy',$filterGroup))->class('d-inline')->open()}}
                                <button type="submit" class="btn btn-icon btn-outline-danger waves-effect confirm">
                                    <i data-feather='trash-2'></i>
                                </button>
                                {{ html()->form()->close()}}
                            </td> 
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center"></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/filters/show.blade.php
@extends('admin.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
     
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('View') @lang('Reservation Blog') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('View') </label>
                                    <p>{{  $ReservationService->name }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="email">@lang('Email') </label>
                                    <p>{{  $ReservationService->email }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="mobile">@lang('Mobile') </label>
                                    <p>{{  $ReservationService->mobile }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="detail">@lang('Detail') </label>
                                    <p>{{  $ReservationService->detail }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
    
        </div>
    </div>
@endsection