routes/admin.php
<?php

use App\Models\Region;
use App\Models\Category;
use App\Models\District;
use App\Models\FilterGroup;
use App\Models\Governorate;
use Illuminate\Http\Request;
use App\Models\Advertisement;
use App\Http\Controllers\Admin\FiltersController;
use App\Http\Controllers\Admin\RegionsController;
use App\Http\Controllers\Admin\DistrictsController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\CustomAuthController;
use App\Http\Controllers\Admin\GovernoratesController;
use App\Http\Controllers\Admin\AdvertisementsController;
require 'breadcrumbs.php';



Route::get('login',[CustomAuthController::class,'login'])->name('login');
Route::get('signup',[CustomAuthController::class,'signup'])->name('signup');
Route::post('postlogin',[CustomAuthController::class,'postlogin'])->name('postlogin'); 
Route::post('signupsave', [CustomAuthController::class,'signupsave'])->name('signupsave'); 
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath','auth' ]
    ], function(){
        Route::resource('governorates', GovernoratesController::class);
        Route::resource('regions', RegionsController::class);
        Route::resource('districts', DistrictsController::class);
        Route::resource('filters', FiltersController::class);
        Route::resource('advertisements', AdvertisementsController::class);
        Route::resource('categories', CategoriesController::class);
        Route::get('getFilters', function (Request $request) {
            $filterGroups = FilterGroup::whereHas('categories', function ($q) use ($request) {
                $q->where('category_id', $request->category_id);
            })->get();
            return view('admin.advertisements.getFilters', compact('filterGroups'));
        })->name('getFilters');

        Route::get('getRegions', function (Request $request) {
            $regions = Region::where('governorate_id', $request->governorate_id)->where('status', 'enabled')->get();
            return view('admin.districts.getRegions', compact('regions'));
        })->name('getRegions');

        Route::get('getDistricts', function (Request $request) {
            $districts = District::where('region_id', $request->region_id)->where('status', 'enabled')->get();
            return view('admin.districts.getDistricts', compact('districts'));
        })->name('getDistricts');
        Route::controller(CustomAuthController::class)->group(function () {
            Route::get('/','home')->name('home'); 
            Route::get('dashboard','dashboard'); 
            Route::get('signout', 'signOut')->name('signout');
            Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
            Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
            Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
            Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
        });
        
    });
    Route::get('home', function () {
        $categories = Category::all();
        $advertisements = Advertisement::all();
        return view('web.home', compact('categories','advertisements'));
    })->name('home');

    Route::get('getgovernorates', function (Request $request) {
        $datas = Governorate::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->get();
        $clickclass = 'governorates';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getgovernorates');

    Route::get('getregions', function (Request $request) {
        $datas = Region::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id)->where('governorate_id',  $request->governorate_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->get();
        $clickclass = 'regions';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getregions');

    Route::get('getdistricts', function (Request $request) {
        $datas = District::whereHas('advertisements', function ($q) use ($request) {
            $q->where('category_id', $request->category_id)->where('governorate_id', $request->governorate_id)
            ->where('region_id', $request->region_id);
        })->get();
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->
        where('region_id', $request->region_id)->get();
        $clickclass = 'districts';
        return view('web.getdata', compact('datas', 'advertisements', 'clickclass'));
    })->name('getdistricts');

    Route::get('getdata', function (Request $request) {
        $advertisements = Advertisement::where('category_id', $request->category_id)->
        where('governorate_id', $request->governorate_id)->
        where('region_id', $request->region_id)->
        where('district_id', $request->district_id)->get();
        $filterGroups = FilterGroup::whereHas('categories', function ($q) use ($request) {
            $q->where('category_id', $request->category_id);
        })->get();
        return view('web.advertisements', compact('advertisements','filterGroups'));
    })->name('getdata');

    // Route::get('web','web/index')->name('home');
// Route::controller(WebController::class)->group(function () {

//     // Route::get('dashboard','dashboard'); 
//     // Route::get('signout', 'signOut')->name('signout');
//     // Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
//     // Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
//     // Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
//     // Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
// });


// Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth', 'checkLogin']], function () {

//     Route::get('/', function () {
//         return view('dashboard.layouts.layout');
//     })->name('index');


//     Route::get('/settings', [SettingController::class, 'index'])->name('settings');

//     Route::post('/settings/update/{setting}', [SettingController::class, 'update'])->name('settings.update');


//     Route::get('/users/all', [UserController::class, 'getUsersDatatable'])->name('users.all');
//     Route::post('/users/delete', [UserController::class, 'delete'])->name('users.delete');


//     Route::get('/category/all', [CategoryController::class, 'getCategoriesDatatable'])->name('category.all');
//     Route::post('/category/delete', [CategoryController::class, 'delete'])->name('category.delete');



//     Route::get('/posts/all', [PostsController::class, 'getPostsDatatable'])->name('posts.all');
//     Route::post('/posts/delete', [PostsController::class, 'delete'])->name('posts.delete');


//     Route::resources([
//         'users' => UserController::class,
//         'category' => CategoryController::class,
//         'posts' => PostsController::class,
//     ]);
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('/', function () {
//     return view('admin.index');
// });

// Route::get('/app', function () {
//     return view('admin.app');
// });


// Route::get('/gest', function () {
//     return view('admin.gest');
// });

// Route::get('/login', function () {
//     return view('admin.auth.login');
// });


// Route::get('/register', function () {
//     return view('admin.auth.register');
// });


// Route::get('/forgot', function () {
//     return view('admin.auth.forgot');
// });


// Route::get('/reset', function () {
//     return view('admin.auth.reset');
// });


// Route::get('/verify', function () {
//     return view('admin.auth.verify');
// }); 

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';
require __DIR__ . '/api.php';


// Route::get('/', [IndexController::class, 'index'])->name('index');
// Route::get('/categories/{category}', [WebsiteCategoryController::class, 'show'])->name('category');
// Route::get('/post/{post}', [PostController::class, 'show'])->name('post');

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\FilterGroup;
use App\Models\Advertisement;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['name','parent_id'];

    public function filterGroups()
    {
        return $this->belongsToMany(FilterGroup::class, 'category_filter_group', 'category_id','filter_group_id');
    }
    
    public function advertisements()
    {
    	return $this->hasMany(Advertisement::class);
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Refregion;
use App\Models\Category;
use App\Models\FilterGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get all the Category
        $categories = Category::all();
        return view('admin.categories.index', compact('categories'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('status', 'enabled')->get();
        $filterGroups = FilterGroup::where('status', 'enabled')->get();
        return view('admin.categories.create', compact('categories','filterGroups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $data = Category::create($request->all());        
        $data->filterGroups()->sync(request('Filters'));      
        return redirect('categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $Category)
    {

        $item_filtergroups = $Category->filterGroups->pluck('id')->toArray();
        $categories = Category::where('status', 'enabled')->get();
        $filterGroups = FilterGroup::where('status', 'enabled')->get();
        return view('admin.categories.edit', compact('Category','categories','filterGroups','item_filtergroups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $Category)
    {
        $Category->update($request->all());
        $Category->filterGroups()->sync(request('Filters'));      
        return redirect('categories');
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $Category)
    {
        $Category->delete();
        return redirect()->back();
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
   <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>

  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('categories.index') }}">@lang('Categories')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('categories.create') }}" >@lang('Add New')</a>
</li>
@endsection


@section('content')
<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('categories.store') }}">
            @csrf
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Add New') @lang('Article') </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" class="d-block">estate</label>
                                <div class="form-check my-50">
                                    <input type="radio" id="validationRadio3" name="estate" class="form-check-input" 
                                    required  value="all"/>
                                    <label class="form-check-label" for="validationRadio3">all</label>
                                </div>
                                <div class="form-check my-50">
                                    <input type="radio" id="validationRadio4" name="estate" class="form-check-input"
                                     required  value="sale"/>
                                    <label class="form-check-label" for="validationRadio4">sale</label>
                                </div>
                                <div class="form-check">
                                    <input type="radio" id="validationRadio4" name="estate" class="form-check-input" required 
                                     value="rent"/>
                                    <label class="form-check-label" for="validationRadio4">rent</label>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Name')</label>
                                <input type="text" id="fp-default" name="name" required 
                                class="form-control "
                                placeholder="Name" />
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Categories')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="parent_id" data-placeholder="">
                                <option value="0">لا يوجد تصنيف رئيسي</option>
                                @foreach ($categories as $category)
                                <option value="{{  $category->id }}">{{  $category->name }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Filter Groups')</label>
                                <select class="form-control select2" name="Filters[]" multiple="">
                                    @foreach($filterGroups as $group)
                                        <option @if(in_array($group->id,old('groups',[])))  selected @endif value="{{$group->id}}">{{$group->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>   
                    </div>
                   
                
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!-- END: Theme JS-->
<script>
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
   <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>

  <!-- END: Page CSS-->
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('categories.index') }}">@lang('Categories')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('categories.create') }}" >@lang('Modify')</a>
</li>
@endsection

@section('content')
<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('categories.update', $Category->id) }}">
            @csrf
            @method('PUT')
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Add New') @lang('Article') </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Name')</label>
                                <input type="text" id="fp-default" name="name" required 
                                class="form-control " value="{{ $Category->name  }}"
                                placeholder="Name" />
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Categories')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="parent_id" data-placeholder="">
                                <option value="0" @if (0 == $Category->parent_id)
                                    selected @endif>لا يوجد تصنيف رئيسي</option>
                                @foreach ($categories as $category)
                                <option value="{{  $category->id }}"  @if ($category->id == $Category->parent_id)
                                    selected @endif>{{  $category->name }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Filter Groups')</label>
                                <select class="form-control select2" name="Filters[]" multiple="">
                                    @foreach($filterGroups as $group)
                                        <option  @if (in_array($group->id, $item_filtergroups))
                                            selected @endif value="{{$group->id}}">{{$group->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>   
                    </div>
                   
                
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!-- END: Theme JS-->
<script>
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('categories.index') }}">@lang('Categories')</a>
</li>
@endsection

@section('content')
<div class="row" id="basic-table">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">@lang('Categories')</h4>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li>
                            <a href="{{route('categories.create')}}"
                               class="btn btn-icon btn-primary waves-effect"
                               data-bs-toggle="tooltip"
                               data-bs-placement="left"
                               title="@lang('Add New')">
                                <i data-feather='plus-square'></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>@lang('Name')</th>
                        <th class="width-150"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($categories as $category)
                        <tr>
                            <td>
                                <span class="fw-bold">{{$category->name}}</span>
                            </td>
                           
                            <td>

                                {{-- <a href="{{route('categories.show',$category)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='eye'></i>
                                </a>  --}}


                                <a href="{{route('categories.edit',$category)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='edit'></i>
                                </a>
                            

                                {{ html()->form('DELETE',route('categories.destroy',$category))->class('d-inline')->open()}}
                                <button type="submit" class="btn btn-icon btn-outline-danger waves-effect confirm">
                                    <i data-feather='trash-2'></i>
                                </button>
                                {{ html()->form()->close()}}
                            </td> 
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center"></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
     
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('View') @lang('Category') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('Name') </label>
                                    <p>{{ $Category->translate($key)->title ?? '' }} </p>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                    
                </div>
    
        </div>
    </div>
@endsection